CREATE TABLE if not exists course (
  course_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   total_workload INTEGER NOT NULL,
   CONSTRAINT pk_course PRIMARY KEY (course_id)
);