CREATE TABLE if not exists users (
   user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    name VARCHAR(255),
    surname VARCHAR(255),
    birth TIMESTAMP WITHOUT TIME ZONE,
    email VARCHAR(255),
    course_name VARCHAR(255),
    start_date TIMESTAMP WITHOUT TIME ZONE,
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    last_access_date TIMESTAMP WITHOUT TIME ZONE,
    permissions VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
 );