CREATE TABLE if not exists course (
  course_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_course PRIMARY KEY (course_id)
);

CREATE TABLE courses_disciplines (
  course_id BIGINT NOT NULL,
   discipline_id BIGINT NOT NULL,
   CONSTRAINT pk_courses_disciplines PRIMARY KEY (course_id, discipline_id)
);

ALTER TABLE courses_disciplines ADD CONSTRAINT fk_coudis_on_course FOREIGN KEY (course_id) REFERENCES course (course_id);

ALTER TABLE courses_disciplines ADD CONSTRAINT fk_coudis_on_disciplines FOREIGN KEY (discipline_id) REFERENCES disciplines (discipline_id);