CREATE TABLE if not exists disciplines (
  discipline_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   workload INTEGER NOT NULL,
   credits INTEGER NOT NULL,
   status VARCHAR(255),
   semester INTEGER NOT NULL,
   grade FLOAT,
   CONSTRAINT pk_disciplines PRIMARY KEY (discipline_id)
);